version: '3'

services:
  elasticsearch:
    container_name: es_container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - elasticsearch_network

  indexer:
    container_name: indexer_container
    build: etl/
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch_network

networks:
  elasticsearch_network:
    driver: bridge
