table_correspondance = {
    'A': 'Adrien',
    'B': 'Baptiste',
    'C': 'Charles',
    'D': 'Dominique',
    'E': 'Emilien',
    'F': 'François',
    'G': 'Gabriel',
    'H': 'Honoré',
    'I': 'Isidore',
    'J': 'Jean',
    'K': 'Kilian',
    'L': 'Léandre',
    'M': 'Maxime',
    'N': 'Noël',
    'O': 'Olivier',
    'P': 'Pascal',
    'Q': 'Quentin',
    'R': 'Redon',
    'S': 'Sébastien',
    'T': 'Théophile',
    'U': 'Urbain',
    'V': 'Valentin',
    'W': 'Wilfried',
    'X': 'Xavier',
    'Y': 'Yannick',
    'Z': 'Zacharie'
}